version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: 
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./jk-profile
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./jk-profile:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    volumes:
      - ./backend:/app
    env_file: 
      - ./backend/.env 
    command: ["celery", "-A", "config.celery", "worker", "-l", "INFO", "--autoscale=2,5"]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  test:
    build:
      context: ./backend
    container_name: django_backend_test
    command: pytest
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis